server.port: 8081

forecast:
    protocol: "https"
    host: "api.open-meteo.com"
    port: 443
    forecastApiPath: "/v1/forecast"
    timeOutInMillis: "5000"
airQuality:
    protocol: "https"
    host: "air-quality-api.open-meteo.com"
    port: 443
    airQualityApiPath: "/v1/air-quality"
    timeOutInMillis: "5000"
#		https:///v1/latitude=52.52&longitude=13.41&hourly=pm10,pm2_5"


otel:
   service:
      name: weather-aggregator-monitor
   exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_GRPC_OTLP_ENDPOINT:http://localhost:4317}
        protocol: grpc      
        logs:
          enabled: true
        traces:
          enabled: true
        metrics:
          enabled: true



logging:
  level:
     root: INFO
     com.github: DEBUG
     io:
      opentelemetry: DEBUG
  pattern:
     console: "%d{ISO8601} %-5level %logger{36} - %msg%n"  # ISO8601 timestamp format
