server.port: 8082

weather:
    protocol: "http"
    host: "${WEATHER_AGGREGATOR_HOST:localhost}"
    port: 8081
    forecastApiPath: "/api/weather"
    timeOutInMillis: "5000"

otel:
   service:
      name: weather-gateway-monitor
   exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_GRPC_OTLP_ENDPOINT:http://localhost:4317}
        protocol: grpc      
        logs:
          enabled: true
        traces:
          enabled: true
        metrics:
          enabled: true



logging:
  level:
     root: INFO
     com.github: DEBUG
     io:
      opentelemetry: DEBUG
  pattern:
     console: "%d{ISO8601} %-5level %logger{36} - %msg%n"  # ISO8601 timestamp format
